package com.harleythetech.sbphmrup.htt.texteditor;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

public class Jframe extends javax.swing.JFrame {
    public Jframe() {
        initComponents();
    }
    @SuppressWarnings("unchecked")
    // all the stuff generated by Netbeans [Lazy to code? Want to just drag and drop stuff and the code will be automated? Well look no more cause Netbeans is Here to make your miserable life easier!]
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Load = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inrea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notepad but with less features HA!");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        Load.setBackground(new java.awt.Color(51, 51, 51));
        Load.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 24)); // NOI18N
        Load.setForeground(new java.awt.Color(255, 255, 255));
        Load.setText("Load");
        Load.setBorderPainted(false);
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        Save.setBackground(new java.awt.Color(51, 51, 51));
        Save.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 24)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setBorderPainted(false);
        Save.setMaximumSize(new java.awt.Dimension(89, 35));
        Save.setMinimumSize(new java.awt.Dimension(89, 35));
        Save.setPreferredSize(new java.awt.Dimension(89, 35));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(51, 51, 51));
        Clear.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 24)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setBorderPainted(false);
        Clear.setMaximumSize(new java.awt.Dimension(89, 35));
        Clear.setMinimumSize(new java.awt.Dimension(89, 35));
        Clear.setPreferredSize(new java.awt.Dimension(89, 35));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        inrea.setBackground(new java.awt.Color(255, 255, 255));
        inrea.setColumns(20);
        inrea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inrea.setForeground(new java.awt.Color(0, 0, 0));
        inrea.setRows(5);
        inrea.setCaretColor(new java.awt.Color(0, 0, 0));
        inrea.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(inrea);
        inrea.getAccessibleContext().setAccessibleName("txtinput");
        inrea.getAccessibleContext().setAccessibleDescription("Input field for editing");

        jLabel1.setFont(new java.awt.Font("Gotham Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simple Text Editor");
        jLabel1.setIconTextGap(0);

        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(218, 218, 218));
        jLabel2.setText("@Harleythetech");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Load, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Load, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Load.getAccessibleContext().setAccessibleDescription("Loads File that needs to be edited");
        Save.getAccessibleContext().setAccessibleDescription("Saves Edited FIle");
        Clear.getAccessibleContext().setAccessibleDescription("Clears Text Input?");

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // Why Clear text when you have CTRL + A then Del or Backspace 
        inrea.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // It;s in the name - Save Action Performed - It saves the file you edited :D
        JFileChooser sfc = new JFileChooser();
        sfc.showSaveDialog(this);
        File sf=sfc.getSelectedFile();
        try{
            try (FileWriter sfw = new FileWriter(sf)) {
                String text=inrea.getText();
                sfw.write(text);
            }
        }catch(IOException ex){
            Logger.getLogger(Jframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SaveActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // File Loader - Because i don't know how to implement drag and drop yet. [OR do i?]
        JFileChooser loader = new JFileChooser();
        int retval = loader.showOpenDialog(this);
        if (retval == JFileChooser.APPROVE_OPTION){
            File load = loader.getSelectedFile();
            System.out.println(load.getAbsolutePath());
            try{
            FileReader fileloaderread = new FileReader(load);
            BufferedReader br = new BufferedReader(fileloaderread);
            inrea.read(br,loader);
            br.close();
            }catch(FileNotFoundException ex){Logger.getLogger(Jframe.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IOException ex) {
                Logger.getLogger(Jframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_LoadActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Load;
    private javax.swing.JButton Save;
    private javax.swing.JTextArea inrea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
/**
 * @author @Harleythetech - Vincent Harley R. Jovellano - ICT102A - [28d54af0-e2e2-4dd2-92db-234854c0119f]
 * @MD5: 384381ae033564c2e5d6736814bac802
 * @SHA1: c39e45c367e4cdbfd6b5e910b03efe1f9bdcd355
 * @SHA256: 91c59d44fa3a8828b7b55924f2006d6e847bc769c9da0334976b93b53db6ccab
 * @SHA512: 47e430b9ad9c9ddd7f5559d66770481e33360e08e82bba131203a01ea6a492413b08bd32fb05f31cde67ce72391620f4fe3ffbeb83cde0a7ba05a8f072423d92
 */